services:
  gravit-server:
    container_name: gravit-server
    image: ${DOCKER_HUB_USERNAME}/gravit-server:latest
    ports:
      - "8520:8080"
    environment:
      - TZ=Asia/Seoul
    networks:
      - mogaktae_js-bridge

  gravit-redis:
    image: redis:latest
    container_name: gravit-redis
    ports:
      - "6386:6379"
    volumes:
      - redis_data:/data
    networks:
      - mogaktae_js-bridge
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  redis_data:

networks:
  mogaktae_js-bridge:
    external: true