services:
  gravit-server:
    container_name: gravit-server
    image: ${DOCKER_HUB_USERNAME}/gravit-server:latest
    ports:
      - "8520:8080"
    environment:
      - TZ=Asia/Seoul
    networks:
      - mogaktae_js-bridge

  js-logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: js-logstash
    volumes:
      - ./logs:/var/log/logstash
    ports:
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    command: ${LOGSTASH_COMMAND}
    networks:
      - mogaktae_js-bridge

networks:
  mogaktae_js-bridge:
    external: true