-- USERS
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- GenerationType.IDENTITY
    email              VARCHAR(255) NOT NULL,
    provider_id        VARCHAR(255) NOT NULL,                               -- User.providerId (snake_case 전략 가정)
    nickname           VARCHAR(50)  NOT NULL,
    handle             VARCHAR(50)  NOT NULL,                               -- unique = true (엔티티)
    level              INTEGER      NOT NULL,
    xp                 INTEGER      NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    profile_img_number INT          NOT NULL,
    is_onboarded       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_users_handle ON users (handle);

-- FRIENDS
CREATE TABLE friends
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- GenerationType.IDENTITY
    follower_id BIGINT NOT NULL,
    followee_id BIGINT NOT NULL,
    CONSTRAINT fk_friends_follower FOREIGN KEY (follower_id) REFERENCES users (id),
    CONSTRAINT fk_friends_followee FOREIGN KEY (followee_id) REFERENCES users (id)
);
