-- 외래 키 제약 조건 비활성화
SET REFERENTIAL_INTEGRITY FALSE;

-- 테이블 데이터 삭제
TRUNCATE TABLE friends;
TRUNCATE TABLE users;
TRUNCATE TABLE user_league;
TRUNCATE TABLE league;
TRUNCATE TABLE season;

-- AUTO_INCREMENT (IDENTITY) 값 초기화
ALTER TABLE friends ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE user_league ALTER COLUMN id RESTART WITH 1;
ALTER TABLE league ALTER COLUMN id RESTART WITH 1;
ALTER TABLE season ALTER COLUMN id RESTART WITH 1;


-- 외래 키 제약 조건 다시 활성화
SET REFERENTIAL_INTEGRITY TRUE;