SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE friend;
TRUNCATE TABLE users;

ALTER TABLE friend ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;