-- V11__add_report.sql

-- 1) report 테이블 추가
CREATE TABLE report
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type  VARCHAR(50) NOT NULL,
    content      TEXT,
    problem_id   BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    is_resolved  BOOLEAN     NOT NULL DEFAULT FALSE,
    submitted_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2) 외래키 제약조건 추가
ALTER TABLE report
    ADD CONSTRAINT fk_report__user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE report
    ADD CONSTRAINT fk_report__problem
        FOREIGN KEY (problem_id) REFERENCES problem (id);