-- V12__add_mission_update_lesson_progress.sql

-- 1) Mission 테이블 추가
CREATE TABLE mission
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_type  VARCHAR(50)                     NOT NULL,
    progress_rate DOUBLE PRECISION                NOT NULL DEFAULT 0.0,
    is_completed  BOOLEAN                         NOT NULL DEFAULT FALSE,
    user_id       BIGINT                          NOT NULL UNIQUE,
    version       BIGINT                          NOT NULL DEFAULT 0
);

-- 2) LessonProgress 테이블에 컬럼 추가
ALTER TABLE lesson_progress
    ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE lesson_progress
    ADD COLUMN learning_time INTEGER NOT NULL DEFAULT 0;

-- 3) Mission 테이블 외래키 제약조건 추가
ALTER TABLE mission
    ADD CONSTRAINT fk_mission__user
        FOREIGN KEY (user_id) REFERENCES users (id);
