-- 공지 테이블 생성
CREATE TABLE IF NOT EXISTS notice (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    summary       VARCHAR(300) NOT NULL,
    content       TEXT  NOT NULL,
    author_id     BIGINT NOT NULL,
    status        VARCHAR(255) NOT NULL,
    pinned        BOOLEAN NOT NULL DEFAULT FALSE,
    published_at  TIMESTAMP(6),
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),

    -- 상태 값 제한 (엔티티와 동일)
    CONSTRAINT notice_status_chk CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),

    -- 작성자 FK (users.id 기준)
    CONSTRAINT fk_notice_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- 조회/정렬 패턴에 맞춘 인덱스 (상태 필터 + pinned/발행일 최신 + id tie-break)
CREATE INDEX IF NOT EXISTS idx_notice_status_pinned_published_id
    ON notice (status, pinned DESC, published_at DESC, id DESC);

-- 작성자별 조회 용이하게 (관리자 화면 등)
CREATE INDEX IF NOT EXISTS idx_notice_author
    ON notice (author_id);
