-- Answer Table
CREATE TABLE answer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id  BIGINT,
    content     VARCHAR(255) NOT NULL,
    explanation TEXT         NOT NULL,
    PRIMARY KEY (id)
);

-- Badge Category Table
CREATE TABLE badge_category
(
    display_order INTEGER      NOT NULL,
    created_at    TIMESTAMP(6),
    id            BIGINT       NOT NULL,
    updated_at    TIMESTAMP(6),
    description   VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Badge Table
CREATE TABLE badge
(
    display_order   INTEGER      NOT NULL,
    icon_id         INTEGER      NOT NULL,
    category_id     BIGINT       NOT NULL,
    created_at      TIMESTAMP(6),
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at      TIMESTAMP(6),
    code            VARCHAR(255) NOT NULL,
    criteria_params JSONB        NOT NULL,
    criteria_type   VARCHAR(255) NOT NULL CHECK (criteria_type IN
                                                 ('PLANET_COMPLETE', 'ALL_PLANETS_COMPLETE', 'STREAK_DAYS',
                                                  'SPEED_QUALIFIED_COUNT', 'MISSION_COUNT')),
    description     VARCHAR(255) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Bookmark Table
CREATE TABLE bookmark
(
    created_at TIMESTAMP(6) NOT NULL,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

-- Chapter Table
CREATE TABLE chapter
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255) NOT NULL,
    title       VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

-- Friends Table
CREATE TABLE friends
(
    created_at  TIMESTAMP(6),
    followee_id BIGINT NOT NULL,
    follower_id BIGINT NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at  TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- League Table
CREATE TABLE league
(
    max_lp     INTEGER     NOT NULL,
    min_lp     INTEGER     NOT NULL,
    sort_order INTEGER     NOT NULL UNIQUE,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

-- Learning Table
CREATE TABLE learning
(
    consecutive_solved_days  INTEGER NOT NULL,
    planet_conquest_rate     INTEGER NOT NULL,
    today_solved             BOOLEAN NOT NULL,
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recent_solved_chapter_id BIGINT  NOT NULL,
    user_id                  BIGINT  NOT NULL UNIQUE,
    version                  BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

-- Lesson Table
CREATE TABLE lesson
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unit_id BIGINT       NOT NULL,
    title   VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Lesson Submission Table
CREATE TABLE lesson_submission
(
    learning_time INTEGER NOT NULL,
    try_count     INTEGER NOT NULL,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lesson_id     BIGINT  NOT NULL,
    user_id       BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

-- Mission Table
CREATE TABLE mission
(
    is_completed  BOOLEAN          NOT NULL,
    progress_rate DOUBLE PRECISION NOT NULL,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT           NOT NULL UNIQUE,
    version       BIGINT           NOT NULL,
    mission_type  VARCHAR(255)     NOT NULL CHECK (mission_type IN ('COMPLETE_LESSON_ONE', 'COMPLETE_LESSONS_TWO',
                                                                    'COMPLETE_LESSONS_THREE', 'PERFECT_LESSON_ONE',
                                                                    'PERFECT_LESSONS_TWO', 'PERFECT_LESSONS_THREE',
                                                                    'LEARNING_MINUTES_TEN', 'LEARNING_MINUTES_FIFTEEN',
                                                                    'LEARNING_MINUTES_TWENTY', 'FOLLOW_NEW_FRIEND')),
    PRIMARY KEY (id)
);

-- Notice Table
CREATE TABLE notice
(
    pinned       BOOLEAN      NOT NULL,
    author_id    BIGINT       NOT NULL,
    created_at   TIMESTAMP(6),
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    published_at TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    content      VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    title        VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Option Table
CREATE TABLE option
(
    is_answer   BOOLEAN      NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id  BIGINT       NOT NULL,
    content     VARCHAR(255) NOT NULL,
    explanation VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Problem Table
CREATE TABLE problem
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lesson_id    BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    instruction  VARCHAR(255) NOT NULL,
    problem_type VARCHAR(255) NOT NULL CHECK (problem_type IN ('SUBJECTIVE', 'OBJECTIVE')),
    PRIMARY KEY (id)
);

-- Problem Submission Table
CREATE TABLE problem_submission
(
    is_correct BOOLEAN NOT NULL,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id BIGINT  NOT NULL,
    user_id    BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

-- Report Table
CREATE TABLE report
(
    is_resolved  BOOLEAN      NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id   BIGINT       NOT NULL,
    submitted_at TIMESTAMP    NOT NULL,
    user_id      BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    report_type  VARCHAR(255) NOT NULL CHECK (report_type IN
                                              ('TYPO_ERROR', 'CONTENT_ERROR', 'ANSWER_ERROR', 'OTHER_ERROR')),
    PRIMARY KEY (id)
);

-- Season Table
CREATE TABLE season
(
    ends_at    TIMESTAMP(6) NOT NULL,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    starts_at  TIMESTAMP(6) NOT NULL,
    season_key VARCHAR(16)  NOT NULL,
    status     VARCHAR(255) NOT NULL CHECK (status IN ('PREP', 'ACTIVE', 'FINALIZING', 'CLOSED')),
    tz         VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_season_key UNIQUE (season_key)
);

-- Unit Table
CREATE TABLE unit
(
    chapter_id  BIGINT       NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255) NOT NULL,
    title       VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- User Badge Table
CREATE TABLE user_badge
(
    badge_id   BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    user_id    BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_badge UNIQUE (user_id, badge_id)
);

-- User League Table
CREATE TABLE user_league
(
    league_point INTEGER NOT NULL,
    created_at   TIMESTAMP(6),
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    league_id    BIGINT  NOT NULL,
    season_id    BIGINT  NOT NULL,
    updated_at   TIMESTAMP(6),
    user_id      BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

-- User League History Table
CREATE TABLE user_league_history
(
    final_lp        INTEGER NOT NULL,
    final_rank      INTEGER,
    created_at      TIMESTAMP(6),
    final_league_id BIGINT  NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    season_id       BIGINT  NOT NULL,
    updated_at      TIMESTAMP(6),
    user_id         BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

-- User Mission Stat Table
CREATE TABLE user_mission_stat
(
    completed_count INTEGER NOT NULL,
    created_at      TIMESTAMP(6),
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at      TIMESTAMP(6),
    user_id         BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

-- User Planet Completion Table
CREATE TABLE user_planet_completion
(
    created_at TIMESTAMP(6),
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    user_id    BIGINT       NOT NULL,
    planet     VARCHAR(255) NOT NULL CHECK (planet IN ('EARTH', 'MOON', 'MERCURY', 'VENUS', 'MARS', 'JUPITER', 'SATURN',
                                                       'URANUS')),
    PRIMARY KEY (id)
);

-- User Qualified Solve Stat Table
CREATE TABLE user_qualified_solve_stat
(
    qualified_count INTEGER NOT NULL,
    created_at      TIMESTAMP(6),
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at      TIMESTAMP(6),
    user_id         BIGINT  NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

-- Users Table
CREATE TABLE users
(
    is_onboarded       BOOLEAN      NOT NULL,
    level              INTEGER      NOT NULL,
    profile_img_number INTEGER      NOT NULL,
    xp                 INTEGER      NOT NULL,
    created_at         TIMESTAMP(6),
    deleted_at         TIMESTAMP(6),
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at         TIMESTAMP(6),
    email              VARCHAR(255) NOT NULL,
    handle             VARCHAR(255) UNIQUE,
    nickname           VARCHAR(255) NOT NULL,
    provider_id        VARCHAR(255) NOT NULL UNIQUE,
    role               VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    status             VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'DELETED')),
    PRIMARY KEY (id)
);

-- Foreign Keys
ALTER TABLE badge
    ADD CONSTRAINT FKclxvp96k01rlpfhwvpnhxcyu6
        FOREIGN KEY (category_id)
            REFERENCES badge_category (id);

ALTER TABLE notice
    ADD CONSTRAINT FKgib4imoxg1fihk96xdsgmu51o
        FOREIGN KEY (author_id)
            REFERENCES users (id);

ALTER TABLE user_badge
    ADD CONSTRAINT FKjqx9n26pk9mqf1qo8f7xvvoq9
        FOREIGN KEY (badge_id)
            REFERENCES badge (id);

ALTER TABLE user_league
    ADD CONSTRAINT FKjgewnbxcaew8vmj89mokyg6ww
        FOREIGN KEY (league_id)
            REFERENCES league (id);

ALTER TABLE user_league
    ADD CONSTRAINT FKn31iqh5e07soe32fndda1gdnj
        FOREIGN KEY (season_id)
            REFERENCES season (id);

ALTER TABLE user_league
    ADD CONSTRAINT FKplytk9obqk5kpon3rugpcsxb7
        FOREIGN KEY (user_id)
            REFERENCES users (id);

ALTER TABLE user_league_history
    ADD CONSTRAINT FKla4qals4md0j3o0kvmnv68274
        FOREIGN KEY (final_league_id)
            REFERENCES league (id);

ALTER TABLE user_league_history
    ADD CONSTRAINT FKbf7lsy7ir4vsq57ubuoklb7ng
        FOREIGN KEY (season_id)
            REFERENCES season (id);

ALTER TABLE user_league_history
    ADD CONSTRAINT FK1pb3eifbgep0gfe0q5ge30kw0
        FOREIGN KEY (user_id)
            REFERENCES users (id);