-- 문의(inquiry) 테이블. 유저가 작성하며 soft delete(@SQLDelete/@SQLRestriction)를 지원한다.
CREATE TABLE inquiry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title      VARCHAR(255) NOT NULL,
    type       VARCHAR(255) NOT NULL CHECK (type IN
                                            ('BUG_REPORT', 'CONTENT_ERROR', 'FEATURE_SUGGESTION', 'OTHER')),
    content    TEXT         NOT NULL,
    status     VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'RESOLVED')),
    user_id    BIGINT       NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 본인 문의 목록 조회(user_id 필터 + id 정렬)용 인덱스.
CREATE INDEX IF NOT EXISTS ix_inquiry_user_id ON inquiry (user_id);

-- 문의 답변(inquiry_answer) 테이블. 어드민이 작성하며 문의와 1:1 (inquiry_id UNIQUE).
-- 쓰기 API는 후속 이슈에서 추가하되, 스키마는 미리 확정해 마이그레이션 churn 을 방지한다.
CREATE TABLE inquiry_answer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    inquiry_id BIGINT NOT NULL UNIQUE,
    content    TEXT   NOT NULL,
    admin_id   BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_inquiry_answer_inquiry FOREIGN KEY (inquiry_id) REFERENCES inquiry (id)
);
