-- V31__split_mission_definition_and_user_progress.sql

-- 1) 정의와 진행을 겸하던 기존 테이블 제거 (진행도는 이관하지 않는다)
DROP TABLE IF EXISTS mission;

-- 2) 미션 정의 테이블: 무엇을 하는 미션인지
CREATE TABLE mission
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                   VARCHAR(255) NOT NULL UNIQUE,
    title                  VARCHAR(255) NOT NULL,
    description            VARCHAR(255),
    target_type            VARCHAR(255) NOT NULL CHECK (target_type IN
                                        ('COMPLETE_LESSON', 'PERFECT_LESSON', 'LEARNING_SECONDS', 'FOLLOW_FRIEND')),
    target_value           INTEGER      NOT NULL CHECK (target_value > 0),
    max_progress_per_event INTEGER,
    award_xp               INTEGER      NOT NULL CHECK (award_xp >= 0),
    weight                 INTEGER      NOT NULL CHECK (weight >= 0),
    status                 VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at             TIMESTAMP(6),
    updated_at             TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 3) 유저 진행 테이블: 유저가 어디까지 했는지
--    하루 1건 배정 규칙을 UNIQUE로 강제한다. 중복 배정은 애플리케이션이 아니라 DB가 막는다
CREATE TABLE user_mission
(
    id             BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT  NOT NULL,
    mission_id     BIGINT  NOT NULL,
    assigned_date  DATE    NOT NULL,
    progress_count INTEGER NOT NULL DEFAULT 0,
    completed_at   TIMESTAMP(6),
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_user_mission_user_date UNIQUE (user_id, assigned_date)
);

-- 4) 기존 MissionType의 미션 정의를 행으로 시딩
--    학습 15분 미션의 목표를 900초로 바로잡는다 (기존 코드는 14분으로 오기입)
--    max_progress_per_event는 1회 제출당 반영 상한이며 학습 시간 미션에만 적용된다 (기존 하드코딩 300초)
--    created_at/updated_at은 now()로 채운다. BaseEntity를 상속시킨 목적(정의 변경 이력)과 일관되게 시딩 시점을 남긴다
INSERT INTO mission (code, title, target_type, target_value, max_progress_per_event, award_xp, weight, status, created_at, updated_at)
VALUES ('COMPLETE_LESSON_ONE',      '레슨 1개 완료하기',            'COMPLETE_LESSON',  1, NULL, 10, 20, 'ACTIVE', now(), now()),
       ('COMPLETE_LESSONS_TWO',     '레슨 2개 완료하기',            'COMPLETE_LESSON',  2, NULL, 15, 10, 'ACTIVE', now(), now()),
       ('COMPLETE_LESSONS_THREE',   '레슨 3개 완료하기',            'COMPLETE_LESSON',  3, NULL, 20,  5, 'ACTIVE', now(), now()),
       ('PERFECT_LESSON_ONE',       '정답율 100%로 레슨 1개 완료하기', 'PERFECT_LESSON',   1, NULL, 30, 16, 'ACTIVE', now(), now()),
       ('PERFECT_LESSONS_TWO',      '정답율 100%로 레슨 2개 완료하기', 'PERFECT_LESSON',   2, NULL, 35,  8, 'ACTIVE', now(), now()),
       ('PERFECT_LESSONS_THREE',    '정답율 100%로 레슨 3개 완료하기', 'PERFECT_LESSON',   3, NULL, 40,  6, 'ACTIVE', now(), now()),
       ('LEARNING_MINUTES_FIVE',    '학습 5분 완료하기',            'LEARNING_SECONDS', 300, 300, 25, 15, 'ACTIVE', now(), now()),
       ('LEARNING_MINUTES_TEN',     '학습 10분 완료하기',           'LEARNING_SECONDS', 600, 300, 35, 10, 'ACTIVE', now(), now()),
       ('LEARNING_MINUTES_FIFTEEN', '학습 15분 완료하기',           'LEARNING_SECONDS', 900, 300, 40,  5, 'ACTIVE', now(), now()),
       ('FOLLOW_NEW_FRIEND',        '새로운 친구 팔로우하기',         'FOLLOW_FRIEND',    1, NULL, 40,  5, 'ACTIVE', now(), now());
