-- V40__add_interview_tables.sql

-- AI 면접 시뮬레이터의 도메인 테이블을 생성한다.
-- 마스터 데이터(카테고리, 기술 스택, 질문, 개념) 시딩은 내용이 확정된 뒤 별도 버전으로 분리한다.
-- FK 제약은 걸지 않는다. 엔티티가 plain ID 컬럼 + 수동 JPQL 조인으로 매핑되며 user_mission과 같은 방식이다.

-- 1) 채점 집계 단위. 공통 CS는 axis가 없고, 직무별은 축(공통/프레임워크/언어)을 가진다
CREATE TABLE interview_category
(
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    mode       VARCHAR(255) NOT NULL CHECK (mode IN ('COMMON_CS', 'JOB_SPECIFIC')),
    name       VARCHAR(255) NOT NULL,
    axis       VARCHAR(255) CHECK (axis IN ('COMMON', 'FRAMEWORK', 'LANGUAGE')),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_category_mode_name UNIQUE (mode, name)
);

-- 2) 온보딩에서 고르는 기술 스택 선택지
CREATE TABLE interview_tech_stack
(
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    job_role     VARCHAR(255) NOT NULL CHECK (job_role IN ('BACKEND', 'FRONTEND', 'ANDROID', 'IOS')),
    code         VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    sort_order   INTEGER      NOT NULL CHECK (sort_order >= 0),
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_tech_stack_code UNIQUE (code)
);

-- 3) 스택의 축별 카테고리 매핑. 한 스택의 한 축이 두 카테고리를 가리키면 채점 집계가 갈라지므로 UNIQUE로 막는다
CREATE TABLE interview_stack_axis
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tech_stack_id BIGINT       NOT NULL,
    axis          VARCHAR(255) NOT NULL CHECK (axis IN ('COMMON', 'FRAMEWORK', 'LANGUAGE')),
    category_id   BIGINT       NOT NULL,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_stack_axis_stack_axis UNIQUE (tech_stack_id, axis)
);

-- 4) 사전 저장된 면접 질문. unit_id는 약점 진단 후 학습을 이어갈 목적지다
CREATE TABLE interview_question
(
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT       NOT NULL,
    unit_id     BIGINT       NOT NULL,
    content     TEXT         NOT NULL,
    difficulty  VARCHAR(255) NOT NULL CHECK (difficulty IN ('HIGH', 'MEDIUM', 'LOW')),
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 5) 질문별 핵심 개념. 인정 기준과 누락 안내 문구는 저장하지 않고 채점 시점에 AI가 판단한다.
--    따라서 name은 채점 프롬프트가 그대로 판정할 수 있는 문장이어야 한다
CREATE TABLE interview_question_concept
(
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT       NOT NULL,
    name        TEXT         NOT NULL,
    type        VARCHAR(255) NOT NULL CHECK (type IN ('ESSENTIAL', 'SUPPLEMENTARY')),
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 6) 면접 세션. 만점(accuracy_max_score, coherence_max_score)은 생성 시점의 문항 수로 계산해 저장한다.
--    배점 정책이 바뀌어도 과거 세션의 만점이 보존된다.
--    tech_stack_id는 JOB_SPECIFIC 모드에서만 채워진다. 직무는 interview_tech_stack.job_role에서 유도한다
CREATE TABLE interview_session
(
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT       NOT NULL,
    mode                VARCHAR(255) NOT NULL CHECK (mode IN ('COMMON_CS', 'JOB_SPECIFIC')),
    input_type          VARCHAR(255) NOT NULL CHECK (input_type IN ('TEXT', 'VOICE')),
    tech_stack_id       BIGINT,
    level               VARCHAR(255) NOT NULL CHECK (level IN ('HIGH', 'MEDIUM', 'LOW')),
    status              VARCHAR(255) NOT NULL CHECK (status IN ('IN_PROGRESS', 'GRADING', 'COMPLETED', 'ABANDONED')),
    accuracy_score      INTEGER      NOT NULL DEFAULT 0 CHECK (accuracy_score >= 0),
    accuracy_max_score  INTEGER      NOT NULL CHECK (accuracy_max_score >= 0),
    coherence_score     INTEGER      NOT NULL DEFAULT 0 CHECK (coherence_score >= 0),
    coherence_max_score INTEGER      NOT NULL CHECK (coherence_max_score >= 0),
    graded_answer_count INTEGER      NOT NULL DEFAULT 0 CHECK (graded_answer_count >= 0),
    started_at          TIMESTAMP(6) NOT NULL,
    ended_at            TIMESTAMP(6),
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 7) 답변. 세션 생성 시 질문마다 PENDING 행을 미리 만들어두고 제출 때 갱신한다.
--    order는 예약어라 display_order를 쓴다
CREATE TABLE interview_answer
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    session_id    BIGINT       NOT NULL,
    question_id   BIGINT       NOT NULL,
    display_order INTEGER      NOT NULL CHECK (display_order > 0),
    status        VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ANSWERED', 'NO_RESPONSE')),
    content       TEXT,
    audio_key     VARCHAR(255),
    answered_at   TIMESTAMP(6),
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_answer_session_order UNIQUE (session_id, display_order)
);

-- 8) 답변 1건의 채점 결과. 답변과 1:1이다.
--    점수 상한은 걸지 않는다. 배점이 바뀔 때마다 마이그레이션을 새로 쳐야 하고, 상한은 채점 코드가 지킬 규칙이다
CREATE TABLE interview_feedback
(
    id                         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    answer_id                  BIGINT       NOT NULL,
    accuracy_score             INTEGER      NOT NULL CHECK (accuracy_score >= 0),
    structure_score            INTEGER      NOT NULL CHECK (structure_score >= 0),
    clarity_score              INTEGER      NOT NULL CHECK (clarity_score >= 0),
    irrelevant_statement_count INTEGER      NOT NULL CHECK (irrelevant_statement_count >= 0),
    accuracy_multiplier        NUMERIC(2, 1) NOT NULL,
    improvement_suggestion     TEXT,
    created_at                 TIMESTAMP(6),
    updated_at                 TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_feedback_answer UNIQUE (answer_id)
);

-- 9) 개념별 전달/누락 판정. covered가 true면 quote만, false면 missing_feedback_text만 의미를 가진다
CREATE TABLE interview_answer_concept_result
(
    id                    BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    answer_id             BIGINT  NOT NULL,
    concept_id            BIGINT  NOT NULL,
    covered               BOOLEAN NOT NULL,
    quote                 TEXT,
    missing_feedback_text TEXT,
    created_at            TIMESTAMP(6),
    updated_at            TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_answer_concept_result UNIQUE (answer_id, concept_id)
);

-- 10) 답변에서 잘못 말한 구간과 교정 문장. 무응답 답변에는 생성하지 않는다
CREATE TABLE interview_answer_wrong_concept
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    answer_id       BIGINT NOT NULL,
    quoted_text     TEXT   NOT NULL,
    correction_text TEXT   NOT NULL,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 11) 조회 인덱스.
--     UNIQUE 제약이 인덱스를 겸하는 (session_id, display_order), (answer_id), (answer_id, concept_id)는 만들지 않는다

-- 세션 생성 시 조건에 맞는 문제 풀을 선별한다
CREATE INDEX IF NOT EXISTS ix_interview_question_category_difficulty
    ON interview_question (category_id, difficulty);

-- 채점 시 질문의 개념 목록을 읽는다
CREATE INDEX IF NOT EXISTS ix_interview_question_concept_question
    ON interview_question_concept (question_id);

-- 온보딩에서 직무별 스택 선택지를 노출 순서대로 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_tech_stack_job_role
    ON interview_tech_stack (job_role, sort_order);

-- 스택 하나에서 축별 카테고리를 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_stack_axis_stack
    ON interview_stack_axis (tech_stack_id);

-- 사용자의 면접 이력을 최신순으로 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_session_user_started
    ON interview_session (user_id, started_at DESC);

-- 세션 상세에서 답변 목록을 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_answer_session
    ON interview_answer (session_id);

-- 답변별 개념 판정을 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_answer_concept_result_answer
    ON interview_answer_concept_result (answer_id);

-- 답변별 잘못된 개념을 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_answer_wrong_concept_answer
    ON interview_answer_wrong_concept (answer_id);
