-- V41__rebuild_interview_tables.sql

-- 면접 ERD 재설계에 따라 V40의 면접 테이블 10개를 모두 버리고 6개 테이블로 다시 만든다.
-- 카테고리, 기술 스택, 스택 축은 열거형(주제 태그, 스택)으로 옮겨져 테이블이 사라지고,
-- 개념별 판정과 오답 인용은 저장하지 않기로 해 결과 테이블 2개도 사라진다.
-- FK 제약은 V40과 같이 걸지 않는다. 엔티티가 plain ID 컬럼으로 매핑된다.

-- 1) 기존 면접 테이블 제거. 재설계 이전 정책으로 만들어진 데이터라 이관하지 않는다
DROP TABLE IF EXISTS interview_answer_wrong_concept;
DROP TABLE IF EXISTS interview_answer_concept_result;
DROP TABLE IF EXISTS interview_feedback;
DROP TABLE IF EXISTS interview_answer;
DROP TABLE IF EXISTS interview_session;
DROP TABLE IF EXISTS interview_question_concept;
DROP TABLE IF EXISTS interview_question;
DROP TABLE IF EXISTS interview_stack_axis;
DROP TABLE IF EXISTS interview_tech_stack;
DROP TABLE IF EXISTS interview_category;

-- 2) 면접 문제. topic은 출제 필터, unit_id는 약점 진단 후 학습을 이어갈 목적지다.
--    등록된 문제는 수정하지 않고 is_active로 출제 대상에서만 제외한다
CREATE TABLE interview_question
(
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    topic        VARCHAR(255) NOT NULL CHECK (topic IN (
                     'DATA_STRUCTURE', 'ALGORITHM', 'DATABASE', 'OPERATING_SYSTEM', 'NETWORK',
                     'SERVER_COMMON', 'WEB_COMMON', 'AOS_COMMON', 'IOS_COMMON',
                     'JAVA', 'KOTLIN', 'NODE_JS', 'PYTHON', 'TYPESCRIPT', 'SWIFT',
                     'SPRING_BOOT', 'NEST_JS', 'DJANGO', 'REACT', 'VUE', 'NEXT_JS', 'COMPOSE', 'SWIFTUI')),
    unit_id      BIGINT       NOT NULL,
    difficulty   VARCHAR(255) NOT NULL CHECK (difficulty IN ('EASY', 'NORMAL', 'HARD')),
    content      TEXT         NOT NULL,
    model_answer TEXT         NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 3) 문제의 핵심 개념. name은 채점 프롬프트가 그대로 판정할 수 있는 문장이다
CREATE TABLE interview_question_concept
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    question_id   BIGINT       NOT NULL,
    name          TEXT         NOT NULL,
    type          VARCHAR(255) NOT NULL CHECK (type IN ('ESSENTIAL', 'SUPPLEMENTARY')),
    display_order INTEGER      NOT NULL CHECK (display_order > 0),
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_question_concept_question_order UNIQUE (question_id, display_order)
);

-- 4) 면접 세션. 만점 세 컬럼은 생성 시점 배점(정확도 14, 구조성 3, 명료성 3) x 5문항의 스냅샷이다.
--    stack은 JOB_SPECIFIC 모드에서만 값을 가진다
CREATE TABLE interview_session
(
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id               BIGINT       NOT NULL,
    attempt_count         BIGINT       NOT NULL,
    mode                  VARCHAR(255) NOT NULL CHECK (mode IN ('COMMON_CS', 'JOB_SPECIFIC')),
    input_type            VARCHAR(255) NOT NULL CHECK (input_type IN ('TEXT', 'VOICE')),
    difficulty            VARCHAR(255) NOT NULL CHECK (difficulty IN ('EASY', 'NORMAL', 'HARD')),
    stack                 VARCHAR(255) CHECK (stack IN (
                              'JAVA_SPRING_BOOT', 'KOTLIN_SPRING_BOOT', 'NODE_NEST', 'PYTHON_DJANGO',
                              'TS_REACT', 'TS_VUE', 'TS_NEXT', 'KOTLIN_COMPOSE', 'SWIFT_SWIFTUI')),
    status                VARCHAR(255) NOT NULL CHECK (status IN ('IN_PROGRESS', 'GRADING', 'GRADING_FAILED', 'COMPLETED', 'ABANDONED')),
    accuracy_score        INTEGER      NOT NULL DEFAULT 0 CHECK (accuracy_score >= 0),
    delivery_score        INTEGER      NOT NULL DEFAULT 0 CHECK (delivery_score >= 0),
    accuracy_max_score    INTEGER      NOT NULL CHECK (accuracy_max_score >= 0),
    structure_max_score   INTEGER      NOT NULL CHECK (structure_max_score >= 0),
    clarity_max_score     INTEGER      NOT NULL CHECK (clarity_max_score >= 0),
    grading_attempt_count INTEGER      NOT NULL DEFAULT 0 CHECK (grading_attempt_count >= 0),
    started_at            TIMESTAMP(6) NOT NULL,
    ended_at              TIMESTAMP(6),
    created_at            TIMESTAMP(6),
    updated_at            TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- 5) 세션에서 고른 주제. COMMON_CS는 선택한 주제 1~5행, JOB_SPECIFIC은 스택 구성 태그 3행을 가진다
CREATE TABLE interview_session_topic
(
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT       NOT NULL,
    topic      VARCHAR(255) NOT NULL CHECK (topic IN (
                   'DATA_STRUCTURE', 'ALGORITHM', 'DATABASE', 'OPERATING_SYSTEM', 'NETWORK',
                   'SERVER_COMMON', 'WEB_COMMON', 'AOS_COMMON', 'IOS_COMMON',
                   'JAVA', 'KOTLIN', 'NODE_JS', 'PYTHON', 'TYPESCRIPT', 'SWIFT',
                   'SPRING_BOOT', 'NEST_JS', 'DJANGO', 'REACT', 'VUE', 'NEXT_JS', 'COMPOSE', 'SWIFTUI')),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_session_topic_session_topic UNIQUE (session_id, topic)
);

-- 6) 답안. 세션 생성 시 문항마다 PENDING 행을 미리 만들고 일괄 제출 때 갱신한다.
--    출제 문제는 생성 후 바뀌지 않으므로 (session_id, question_id)도 유일하다
CREATE TABLE interview_answer
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    session_id    BIGINT       NOT NULL,
    question_id   BIGINT       NOT NULL,
    display_order INTEGER      NOT NULL CHECK (display_order BETWEEN 1 AND 5),
    status        VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ANSWERED', 'NO_RESPONSE')),
    content       TEXT,
    audio_key     VARCHAR(255),
    answered_at   TIMESTAMP(6),
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_answer_session_order UNIQUE (session_id, display_order),
    CONSTRAINT uq_interview_answer_session_question UNIQUE (session_id, question_id)
);

-- 7) 답안 1건의 채점 결과. 답안과 1:1이다.
--    무응답 문항은 세 점수가 0이고 기본 비율, 감점 배율, 관계없는 발화 수, 개선 제안이 NULL이다.
--    점수 상한은 걸지 않는다. 배점이 바뀔 때마다 마이그레이션을 새로 쳐야 하고, 상한은 채점 코드가 지킬 규칙이다
CREATE TABLE interview_feedback
(
    id                         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    answer_id                  BIGINT        NOT NULL,
    accuracy_score             INTEGER       NOT NULL CHECK (accuracy_score >= 0),
    structure_score            INTEGER       NOT NULL CHECK (structure_score >= 0),
    clarity_score              INTEGER       NOT NULL CHECK (clarity_score >= 0),
    accuracy_base_ratio        NUMERIC(4, 3),
    accuracy_multiplier        NUMERIC(2, 1),
    irrelevant_statement_count INTEGER       CHECK (irrelevant_statement_count >= 0),
    improvement_suggestion     TEXT,
    created_at                 TIMESTAMP(6),
    updated_at                 TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_interview_feedback_answer UNIQUE (answer_id)
);

-- 8) 조회 인덱스. UNIQUE 제약이 인덱스를 겸하는 조합은 만들지 않는다.
--    그 밖의 인덱스는 조회 API 구현 시 실측한 뒤 추가한다

-- 세션 생성 시 태그와 난이도로 활성 문제 풀을 선별한다
CREATE INDEX IF NOT EXISTS ix_interview_question_topic_difficulty
    ON interview_question (topic, difficulty);

-- 사용자의 응시 이력과 시도 차수를 조회한다
CREATE INDEX IF NOT EXISTS ix_interview_session_user_started
    ON interview_session (user_id, started_at DESC);
