-- V42__add_user_daily_activity.sql

-- 일자별 활성 이력 (관리자 대시보드 DAU/MAU 집계용)
-- users.last_accessed_at 은 최신 값만 덮어써 과거 추이를 만들 수 없으므로 별도 이력으로 분리
-- FK 를 걸지 않는다. 탈퇴 후 실제 삭제 시에도 이력을 남겨 과거 집계 수치가 소급 변경되지 않게 한다
-- UNIQUE 선행 컬럼을 activity_date 로 두어 기간 집계의 범위 스캔과 멱등 insert 를 인덱스 하나로 처리한다
CREATE TABLE IF NOT EXISTS user_daily_activity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT NOT NULL,
    activity_date DATE   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_daily_activity_date_user
        UNIQUE (activity_date, user_id)
);
