-- V9__update_problem_add_option.sql

-- 1) problem 테이블의 options 필드 삭제 및 content 필드 추가
ALTER TABLE problem DROP COLUMN IF EXISTS options;
ALTER TABLE problem ADD COLUMN content TEXT NOT NULL DEFAULT '';

-- 2) option 테이블 추가
CREATE TABLE option
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id  BIGINT  NOT NULL,
    content     TEXT    NOT NULL,
    explanation TEXT    NOT NULL,
    is_answer   BOOLEAN NOT NULL
);

-- 3) 옵션 테이블에 외래키 추가
ALTER TABLE option
    ADD CONSTRAINT fk_option__problem
        FOREIGN KEY (problem_id) REFERENCES problem (id);