name: CI pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: run test code on gradle
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up JDK with version 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: run test
        run: |
          chmod +x ./gradlew
          ./gradlew --info test

      - name: display test result
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/test/TEST-*.xml